{{- if (.Values.gatewayCRDInstaller.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-gateway-crd-installer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ .Release.Name }}-gateway-crd-installer
    spec:
      serviceAccountName: {{ .Release.Name }}-gateway-crd-installer
      containers:
      - name: gateway-crd-installer
        image: "{{ .Values.gatewayCRDInstaller.image.repository }}:{{ .Values.gatewayCRDInstaller.image.tag }}"
{{/*        env:*/}}
{{/*        - name: KUBERNETES_SERVICE_HOST*/}}
{{/*          valueFrom:*/}}
{{/*            fieldRef:*/}}
{{/*              apiVersion: v1*/}}
{{/*              fieldPath: status.podIP*/}}
{{/*        - name: KUBERNETES_SERVICE_PORT*/}}
{{/*          value: "6443"*/}}
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing Gateway API CRDs: {{ .Values.gatewayCRDInstaller.version }}/{{ .Values.gatewayCRDInstaller.channel }}"
          {{- range $index, $value := .Values.gatewayCRDInstaller.resources }}
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ $.Values.gatewayCRDInstaller.version }}/config/crd/{{ $.Values.gatewayCRDInstaller.channel }}/{{ $value }}.yaml
          {{- end }}

          echo "Successfully installed Gateway API CRDs."
      restartPolicy: OnFailure
      tolerations:
        - operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: PreferNoSchedule
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: PreferNoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      hostNetwork: true
{{- end }}
