apiVersion: v2
appVersion: 0.1.0
description: Deploy the Solr CRDs.
icon: https://www.kubeblog.com/wp-content/uploads/2024/09/gateway-api-logo-1.png
name: solr-operator
type: application
version: 0.1.0
